import type { ProductStatus } from '@/types/prisma-enums';

export type NovaeProductDef = {
  sku: string;
  name: string;
  nameAr: string;
  description: string;
  descriptionAr: string;
  category: string;
  sellingPrice: number;
  compareAtPrice?: number;
  costPrice?: number;
  status: ProductStatus;
  isFeatured?: boolean;
  initialStock: number;
  lowStockThreshold?: number;
  tags?: string[];
  seoTitle?: string;
  seoDescription?: string;
  options?: { name: string; values: string[] }[];
  variants?: {
    sku: string;
    name?: string;
    sellingPrice: number;
    compareAtPrice?: number;
    optionValues?: string[];
    initialStock?: number;
    lowStockThreshold?: number;
  }[];
};

export const NOVAE_CATEGORIES = [
  { slug: 'clothing', name: 'Clothing', nameAr: 'ملابس', position: 0 },
  { slug: 'bags', name: 'Bags', nameAr: 'حقائب', position: 1 },
  { slug: 'accessories', name: 'Accessories', nameAr: 'إكسسوارات', position: 2 },
  { slug: 'beauty', name: 'Beauty', nameAr: 'جمال', position: 3 },
  { slug: 'home', name: 'Home', nameAr: 'منزل', position: 4 },
  { slug: 'lifestyle', name: 'Lifestyle', nameAr: 'أسلوب حياة', position: 5 },
  { slug: 'new-arrivals', name: 'New Arrivals', nameAr: 'وصل حديثاً', position: 6 },
  { slug: 'best-sellers', name: 'Best Sellers', nameAr: 'الأكثر مبيعاً', position: 7 },
] as const;

export const NOVAE_COLLECTIONS = [
  { slug: 'new-season', name: 'New Season', description: 'Fresh arrivals for the season ahead.' },
  { slug: 'essentials', name: 'Essentials', description: 'Everyday pieces you reach for again and again.' },
  { slug: 'everyday-edit', name: 'Everyday Edit', description: 'Curated staples for modern living.' },
  { slug: 'best-sellers', name: 'Best Sellers', description: 'Customer favorites.' },
  { slug: 'under-150', name: 'Under ₪150', description: 'Accessible pieces under ₪150.' },
  { slug: 'gifts', name: 'Gifts', description: 'Thoughtful gifts for every occasion.' },
  { slug: 'travel-edit', name: 'Travel Edit', description: 'Pack light, travel well.' },
  { slug: 'home-edit', name: 'Home Edit', description: 'Elevate your space.' },
] as const;

export const NOVAE_PRODUCTS: NovaeProductDef[] = [
  // ─── Clothing (10) ───────────────────────────────────────────────
  {
    sku: 'NV-CL-001',
    name: 'Essential Overshirt',
    nameAr: 'قميص أوفرشيرت أساسي',
    description: 'Structured cotton overshirt with a relaxed silhouette. Layer over tees or wear solo.',
    descriptionAr: 'قميص قطني منظم بقصة مريحة. مثالي للطبقات أو للارتداء منفرداً.',
    category: 'clothing',
    sellingPrice: 28900,
    compareAtPrice: 32900,
    costPrice: 12000,
    status: 'ACTIVE',
    isFeatured: true,
    initialStock: 32,
    lowStockThreshold: 8,
    tags: ['bestseller', 'featured'],
    options: [{ name: 'Size', values: ['XS', 'S', 'M', 'L', 'XL'] }, { name: 'Color', values: ['Black', 'Cream', 'Olive'] }],
    variants: [
      { sku: 'NV-CL-001-BK-S', name: 'Black / S', sellingPrice: 28900, optionValues: ['S', 'Black'], initialStock: 12 },
      { sku: 'NV-CL-001-CR-M', name: 'Cream / M', sellingPrice: 28900, optionValues: ['M', 'Cream'], initialStock: 10 },
      { sku: 'NV-CL-001-OL-L', name: 'Olive / L', sellingPrice: 28900, optionValues: ['L', 'Olive'], initialStock: 10 },
    ],
  },
  {
    sku: 'NV-CL-002',
    name: 'Relaxed Linen Shirt',
    nameAr: 'قميص الكتان اليومي',
    description: 'Breathable linen with a soft drape. Perfect for warm days and evening strolls.',
    descriptionAr: 'كتان خفيف بملمس ناعم. مثالي للأيام الدافئة والسهرات الهادئة.',
    category: 'clothing',
    sellingPrice: 24900,
    costPrice: 9800,
    status: 'ACTIVE',
    isFeatured: true,
    initialStock: 45,
    tags: ['new'],
    options: [{ name: 'Size', values: ['S', 'M', 'L', 'XL'] }],
    variants: [
      { sku: 'NV-CL-002-S', sellingPrice: 24900, optionValues: ['S'], initialStock: 12 },
      { sku: 'NV-CL-002-M', sellingPrice: 24900, optionValues: ['M'], initialStock: 15 },
      { sku: 'NV-CL-002-L', sellingPrice: 24900, optionValues: ['L'], initialStock: 18 },
    ],
  },
  {
    sku: 'NV-CL-003',
    name: 'Everyday Knit',
    nameAr: 'كنزة يومية ناعمة',
    description: 'Fine-gauge knit with a clean neckline. A wardrobe foundation piece.',
    descriptionAr: 'حياكة ناعمة بخط عنق بسيط. قطعة أساسية في خزانتك.',
    category: 'clothing',
    sellingPrice: 19900,
    costPrice: 7500,
    status: 'ACTIVE',
    initialStock: 28,
    lowStockThreshold: 6,
  },
  {
    sku: 'NV-CL-004',
    name: 'Structured Cotton Jacket',
    nameAr: 'جاكيت القطن المنظم',
    description: 'Tailored cotton jacket with interior pockets and matte buttons.',
    descriptionAr: 'جاكيت قطني منظم بجيوب داخلية وأزرار مطفية.',
    category: 'clothing',
    sellingPrice: 45900,
    compareAtPrice: 52000,
    costPrice: 19000,
    status: 'ACTIVE',
    isFeatured: true,
    initialStock: 18,
    tags: ['bestseller'],
    options: [{ name: 'Size', values: ['S', 'M', 'L'] }],
    variants: [
      { sku: 'NV-CL-004-S', sellingPrice: 45900, optionValues: ['S'], initialStock: 6 },
      { sku: 'NV-CL-004-M', sellingPrice: 45900, optionValues: ['M'], initialStock: 7 },
      { sku: 'NV-CL-004-L', sellingPrice: 45900, optionValues: ['L'], initialStock: 5 },
    ],
  },
  {
    sku: 'NV-CL-005',
    name: 'Soft Rib Top',
    nameAr: 'توب ريب ناعم',
    description: 'Ribbed cotton top with a flattering fit. Pairs with everything.',
    descriptionAr: 'توب قطني مضلع بقصة أنيقة. يتناسق مع كل شيء.',
    category: 'clothing',
    sellingPrice: 12900,
    costPrice: 4200,
    status: 'ACTIVE',
    initialStock: 55,
  },
  {
    sku: 'NV-CL-006',
    name: 'Classic Wide Trousers',
    nameAr: 'بنطال واسع كلاسيكي',
    description: 'High-rise wide-leg trousers in a fluid drape. Office to evening.',
    descriptionAr: 'بنطال واسع بخصر مرتفع وقصة انسيابية. من المكتب إلى المساء.',
    category: 'clothing',
    sellingPrice: 27900,
    costPrice: 11000,
    status: 'ACTIVE',
    initialStock: 22,
    options: [{ name: 'Size', values: ['XS', 'S', 'M', 'L'] }],
    variants: [
      { sku: 'NV-CL-006-S', sellingPrice: 27900, optionValues: ['S'], initialStock: 8 },
      { sku: 'NV-CL-006-M', sellingPrice: 27900, optionValues: ['M'], initialStock: 8 },
      { sku: 'NV-CL-006-L', sellingPrice: 27900, optionValues: ['L'], initialStock: 6 },
    ],
  },
  {
    sku: 'NV-CL-007',
    name: 'Studio Blazer',
    nameAr: 'بليزر ستوديو',
    description: 'Single-breasted blazer with soft shoulders. Elevated everyday tailoring.',
    descriptionAr: 'بليزر بكتف ناعم وتفصيل يومي راقٍ.',
    category: 'clothing',
    sellingPrice: 52900,
    costPrice: 22000,
    status: 'ACTIVE',
    initialStock: 14,
    lowStockThreshold: 4,
  },
  {
    sku: 'NV-CL-008',
    name: 'Minimal Long Dress',
    nameAr: 'فستان طويل مينيمال',
    description: 'Column silhouette dress in matte jersey. Effortless and refined.',
    descriptionAr: 'فستان بقصة عمودية من جيرسي مطفي. أنيق بلا مجهود.',
    category: 'clothing',
    sellingPrice: 38900,
    costPrice: 15000,
    status: 'ACTIVE',
    isFeatured: true,
    initialStock: 20,
  },
  {
    sku: 'NV-CL-009',
    name: 'Merino Crew Sweater',
    nameAr: 'سويتر ميرينو دائري',
    description: 'Lightweight merino wool crewneck. Seasonless layering essential.',
    descriptionAr: 'سويتر ميرينو خفيف بخط عنق دائري. أساسي لكل المواسم.',
    category: 'clothing',
    sellingPrice: 31900,
    costPrice: 13000,
    status: 'ACTIVE',
    initialStock: 7,
    lowStockThreshold: 5,
    tags: ['low-stock'],
  },
  {
    sku: 'NV-CL-010',
    name: 'Archive Denim Jacket',
    nameAr: 'جاكيت دنيم أرشيفي',
    description: 'Vintage-wash denim with brushed hardware. Limited restock.',
    descriptionAr: 'دنيم بغسيل كلاسيكي وتفاصيل معدنية ناعمة. كمية محدودة.',
    category: 'clothing',
    sellingPrice: 34900,
    costPrice: 14000,
    status: 'ACTIVE',
    initialStock: 0,
    tags: ['out-of-stock'],
  },
  // ─── Bags (5) ────────────────────────────────────────────────────
  {
    sku: 'NV-BG-001',
    name: 'Atelier Tote',
    nameAr: 'حقيبة أتيليه',
    description: 'Spacious leather tote with interior organizer. Crafted for daily carry.',
    descriptionAr: 'حقيبة جلد واسعة مع منظم داخلي. مصممة للحمل اليومي.',
    category: 'bags',
    sellingPrice: 42900,
    compareAtPrice: 48900,
    costPrice: 18000,
    status: 'ACTIVE',
    isFeatured: true,
    initialStock: 24,
    tags: ['bestseller', 'featured'],
    options: [{ name: 'Color', values: ['Black', 'Tan', 'Stone'] }],
    variants: [
      { sku: 'NV-BG-001-BK', name: 'Black', sellingPrice: 42900, optionValues: ['Black'], initialStock: 10 },
      { sku: 'NV-BG-001-TN', name: 'Tan', sellingPrice: 42900, optionValues: ['Tan'], initialStock: 8 },
      { sku: 'NV-BG-001-ST', name: 'Stone', sellingPrice: 42900, optionValues: ['Stone'], initialStock: 6 },
    ],
  },
  {
    sku: 'NV-BG-002',
    name: 'Daily Crossbody',
    nameAr: 'حقيبة كروس يومية',
    description: 'Compact crossbody with adjustable strap. Hands-free convenience.',
    descriptionAr: 'حقيبة كروس مدمجة بحزام قابل للتعديل.',
    category: 'bags',
    sellingPrice: 27900,
    costPrice: 11000,
    status: 'ACTIVE',
    initialStock: 35,
  },
  {
    sku: 'NV-BG-003',
    name: 'Mini Shoulder Bag',
    nameAr: 'حقيبة كتف ميني',
    description: 'Sculpted mini bag with magnetic closure. Evening-ready.',
    descriptionAr: 'حقيبة ميني منحوتة بإغلاق مغناطيسي. مثالية للمساء.',
    category: 'bags',
    sellingPrice: 31900,
    costPrice: 12500,
    status: 'ACTIVE',
    initialStock: 19,
  },
  {
    sku: 'NV-BG-004',
    name: 'Soft Leather Tote',
    nameAr: 'حقيبة جلد ناعمة',
    description: 'Unstructured leather tote that molds to your routine.',
    descriptionAr: 'حقيبة جلد ناعمة بلا هيكل صلب تتكيف مع يومك.',
    category: 'bags',
    sellingPrice: 38900,
    costPrice: 16000,
    status: 'ACTIVE',
    initialStock: 2,
    lowStockThreshold: 3,
    tags: ['critical-stock'],
  },
  {
    sku: 'NV-BG-005',
    name: 'Compact Weekender',
    nameAr: 'حقيبة ويكند مدمجة',
    description: 'Weekend bag with zip closure and interior pocket. Travel light.',
    descriptionAr: 'حقيبة سفر صغيرة بسحاب وجيب داخلي.',
    category: 'bags',
    sellingPrice: 45900,
    costPrice: 18500,
    status: 'ACTIVE',
    initialStock: 15,
  },
  // ─── Accessories (6) ─────────────────────────────────────────────
  {
    sku: 'NV-AC-001',
    name: 'Sculpted Ring',
    nameAr: 'خاتم منحوت',
    description: 'Sterling silver ring with organic form. Hand-finished.',
    descriptionAr: 'خاتم فضة بشكل عضوي وتشطيب يدوي.',
    category: 'accessories',
    sellingPrice: 18900,
    costPrice: 6500,
    status: 'ACTIVE',
    initialStock: 40,
  },
  {
    sku: 'NV-AC-002',
    name: 'Minimal Chain',
    nameAr: 'سلسلة مينيمال',
    description: 'Fine chain necklace in brushed gold tone. Layer or wear alone.',
    descriptionAr: 'سلسلة رفيعة بلون ذهبي مطفي. للطبقات أو منفردة.',
    category: 'accessories',
    sellingPrice: 14900,
    costPrice: 4800,
    status: 'ACTIVE',
    isFeatured: true,
    initialStock: 50,
  },
  {
    sku: 'NV-AC-003',
    name: 'Everyday Watch',
    nameAr: 'ساعة يومية',
    description: 'Slim profile watch with leather strap. Understated precision.',
    descriptionAr: 'ساعة بملف رفيع وحزام جلد. دقة هادئة.',
    category: 'accessories',
    sellingPrice: 59900,
    compareAtPrice: 69900,
    costPrice: 25000,
    status: 'ACTIVE',
    initialStock: 12,
    tags: ['premium'],
  },
  {
    sku: 'NV-AC-004',
    name: 'Signature Bracelet',
    nameAr: 'سوار سيغنتشر',
    description: 'Cuff bracelet with engraved detail. A NOVAÉ signature piece.',
    descriptionAr: 'سوار كف بنقشة دقيقة. قطعة سيغنتشر من نوفاي.',
    category: 'accessories',
    sellingPrice: 22900,
    costPrice: 8500,
    status: 'ACTIVE',
    initialStock: 28,
  },
  {
    sku: 'NV-AC-005',
    name: 'Essential Sunglasses',
    nameAr: 'نظارات أساسية',
    description: 'Acetate frames with UV protection. Timeless square shape.',
    descriptionAr: 'إطار أسيتات بحماية UV وشكل مربع كلاسيكي.',
    category: 'accessories',
    sellingPrice: 27900,
    costPrice: 9000,
    status: 'ACTIVE',
    initialStock: 33,
  },
  {
    sku: 'NV-AC-006',
    name: 'Silk Scarf',
    nameAr: 'وشاح حرير',
    description: 'Printed silk scarf in muted botanical motif.',
    descriptionAr: 'وشاح حرير بطبعة نباتية هادئة.',
    category: 'accessories',
    sellingPrice: 16900,
    costPrice: 5500,
    status: 'DRAFT',
    initialStock: 0,
  },
  // ─── Beauty (6) ──────────────────────────────────────────────────
  {
    sku: 'NV-BT-001',
    name: 'Daily Face Mist',
    nameAr: 'رذاذ الوجه اليومي',
    description: 'Hydrating face mist with rose and aloe. Refresh anytime.',
    descriptionAr: 'رذاذ مرطب بالورد والألوفيرا. انتعاش في أي وقت.',
    category: 'beauty',
    sellingPrice: 8900,
    costPrice: 2800,
    status: 'ACTIVE',
    initialStock: 85,
    options: [{ name: 'Size', values: ['50ml', '100ml'] }],
    variants: [
      { sku: 'NV-BT-001-50', name: '50ml', sellingPrice: 8900, optionValues: ['50ml'], initialStock: 50 },
      { sku: 'NV-BT-001-100', name: '100ml', sellingPrice: 12900, optionValues: ['100ml'], initialStock: 35 },
    ],
  },
  {
    sku: 'NV-BT-002',
    name: 'Hydrating Serum',
    nameAr: 'سيروم الترطيب',
    description: 'Lightweight hyaluronic serum for deep hydration.',
    descriptionAr: 'سيروم خفيف بالهيالورونيك لترطيب عميق.',
    category: 'beauty',
    sellingPrice: 14900,
    costPrice: 5200,
    status: 'ACTIVE',
    isFeatured: true,
    initialStock: 42,
    tags: ['bestseller'],
  },
  {
    sku: 'NV-BT-003',
    name: 'Soft Glow Cream',
    nameAr: 'كريم التوهج الناعم',
    description: 'Daily moisturizer with subtle luminosity. Non-greasy finish.',
    descriptionAr: 'مرطب يومي بتوهج خفيف وملمس غير دهني.',
    category: 'beauty',
    sellingPrice: 11900,
    costPrice: 4000,
    status: 'ACTIVE',
    initialStock: 38,
  },
  {
    sku: 'NV-BT-004',
    name: 'Botanical Body Oil',
    nameAr: 'زيت الجسم النباتي',
    description: 'Nourishing body oil with botanical extracts. Absorbs quickly.',
    descriptionAr: 'زيت جسم مغذٍ بمستخلصات نباتية يمتص بسرعة.',
    category: 'beauty',
    sellingPrice: 13900,
    costPrice: 4800,
    status: 'ACTIVE',
    initialStock: 30,
  },
  {
    sku: 'NV-BT-005',
    name: 'Gentle Cleanser',
    nameAr: 'منظف لطيف',
    description: 'pH-balanced cleanser that respects skin barrier.',
    descriptionAr: 'منظف متوازن الحموية يحافظ على حاجز البشرة.',
    category: 'beauty',
    sellingPrice: 9900,
    costPrice: 3200,
    status: 'ACTIVE',
    initialStock: 60,
  },
  {
    sku: 'NV-BT-006',
    name: 'Night Recovery Balm',
    nameAr: 'بلسم التعافي الليلي',
    description: 'Rich overnight balm for dry and tired skin.',
    descriptionAr: 'بلسم ليلي غني للبشرة الجافة والمتعبة.',
    category: 'beauty',
    sellingPrice: 15900,
    costPrice: 5800,
    status: 'ARCHIVED',
    initialStock: 0,
  },
  // ─── Home (6) ────────────────────────────────────────────────────
  {
    sku: 'NV-HM-001',
    name: 'Ceramic Mug',
    nameAr: 'كوب سيراميك',
    description: 'Hand-glazed ceramic mug. 320ml capacity.',
    descriptionAr: 'كوب سيراميك بطلاء يدوي. سعة 320 مل.',
    category: 'home',
    sellingPrice: 6900,
    costPrice: 2200,
    status: 'ACTIVE',
    initialStock: 72,
  },
  {
    sku: 'NV-HM-002',
    name: 'Linen Candle',
    nameAr: 'شمعة الكتان',
    description: 'Soy wax candle with linen and cedar notes. 45-hour burn.',
    descriptionAr: 'شمعة شمع صويا برائحة كتان وأرز. تحترق 45 ساعة.',
    category: 'home',
    sellingPrice: 11900,
    costPrice: 4000,
    status: 'ACTIVE',
    isFeatured: true,
    initialStock: 48,
  },
  {
    sku: 'NV-HM-003',
    name: 'Stone Tray',
    nameAr: 'صينية حجرية',
    description: 'Travertine tray for jewelry, keys, or ritual objects.',
    descriptionAr: 'صينية ترافرتين للمجوهرات أو المفاتيح أو قطع الديكور.',
    category: 'home',
    sellingPrice: 14900,
    costPrice: 5500,
    status: 'ACTIVE',
    initialStock: 25,
  },
  {
    sku: 'NV-HM-004',
    name: 'Minimal Vase',
    nameAr: 'مزهرية مينيمال',
    description: 'Matte ceramic vase with narrow neck. Single stem perfect.',
    descriptionAr: 'مزهرية سيراميك مطفية بعنق ضيق. مثالية لغصن واحد.',
    category: 'home',
    sellingPrice: 12900,
    costPrice: 4500,
    status: 'ACTIVE',
    initialStock: 31,
  },
  {
    sku: 'NV-HM-005',
    name: 'Soft Throw',
    nameAr: 'بطانية ناعمة',
    description: 'Cotton-blend throw with brushed finish. Cozy without bulk.',
    descriptionAr: 'بطانية قطن مخلوط بملمس ناعم. دفء بدون ثقل.',
    category: 'home',
    sellingPrice: 24900,
    costPrice: 9500,
    status: 'ACTIVE',
    initialStock: 18,
  },
  {
    sku: 'NV-HM-006',
    name: 'Table Linen Set',
    nameAr: 'طقم مفارش طاولة',
    description: 'Set of four linen napkins in natural tone.',
    descriptionAr: 'طقم من أربع مناديل كتان بلون طبيعي.',
    category: 'home',
    sellingPrice: 8900,
    costPrice: 3000,
    status: 'ACTIVE',
    initialStock: 40,
  },
  // ─── Lifestyle (5) ───────────────────────────────────────────────
  {
    sku: 'NV-LS-001',
    name: 'Everyday Journal',
    nameAr: 'دفتر يومي',
    description: 'Lay-flat journal with 160 pages of premium paper.',
    descriptionAr: 'دفتر بفتح مسطح و160 صفحة ورق فاخر.',
    category: 'lifestyle',
    sellingPrice: 7900,
    costPrice: 2500,
    status: 'ACTIVE',
    initialStock: 55,
  },
  {
    sku: 'NV-LS-002',
    name: 'Travel Pouch',
    nameAr: 'حقيبة سفر صغيرة',
    description: 'Water-resistant pouch for cables, cosmetics, and essentials.',
    descriptionAr: 'حقيبة مقاومة للماء للكابلات ومستحضرات التجميل.',
    category: 'lifestyle',
    sellingPrice: 9900,
    costPrice: 3200,
    status: 'ACTIVE',
    initialStock: 44,
  },
  {
    sku: 'NV-LS-003',
    name: 'Premium Water Bottle',
    nameAr: 'قارورة مياه فاخرة',
    description: 'Insulated stainless steel bottle. 500ml.',
    descriptionAr: 'قارورة ستيل معزولة. سعة 500 مل.',
    category: 'lifestyle',
    sellingPrice: 12900,
    costPrice: 4500,
    status: 'ACTIVE',
    initialStock: 36,
  },
  {
    sku: 'NV-LS-004',
    name: 'Essential Tote',
    nameAr: 'حقيبة أساسية',
    description: 'Canvas tote with interior pocket. Market to studio.',
    descriptionAr: 'حقيبة قماش بجيب داخلي. من السوق إلى الاستوديو.',
    category: 'lifestyle',
    sellingPrice: 8900,
    costPrice: 2800,
    status: 'ACTIVE',
    initialStock: 65,
  },
  {
    sku: 'NV-LS-005',
    name: 'Daily Organizer',
    nameAr: 'منظم يومي',
    description: 'Desk organizer in matte finish. Keeps essentials in reach.',
    descriptionAr: 'منظم مكتب بلمسة مطفية. يبقي أساسياتك في متناول اليد.',
    category: 'lifestyle',
    sellingPrice: 14900,
    costPrice: 5200,
    status: 'ACTIVE',
    initialStock: 22,
  },
  // ─── Additional pieces to reach 42 ─────────────────────────────
  {
    sku: 'NV-CL-011',
    name: 'Pleated Midi Skirt',
    nameAr: 'تنورة ميدي مطوية',
    description: 'Fluid pleated midi skirt with elastic waist. Movement and ease.',
    descriptionAr: 'تنورة ميدي مطوية بخصر مطاطي. حركة وراحة.',
    category: 'clothing',
    sellingPrice: 26900,
    costPrice: 10500,
    status: 'ACTIVE',
    initialStock: 16,
  },
  {
    sku: 'NV-AC-007',
    name: 'Leather Card Holder',
    nameAr: 'حافظة بطاقات جلدية',
    description: 'Slim card holder with four slots. Fits any pocket.',
    descriptionAr: 'حافظة بطاقات رفيعة بأربع فتحات.',
    category: 'accessories',
    sellingPrice: 9900,
    costPrice: 3200,
    status: 'ACTIVE',
    initialStock: 58,
  },
  {
    sku: 'NV-BT-007',
    name: 'Lip Treatment Oil',
    nameAr: 'زيت علاج الشفاه',
    description: 'Nourishing lip oil with subtle shine. Vanilla note.',
    descriptionAr: 'زيت شفاه مغذٍ بلمعان خفيف ونفحة فانيلا.',
    category: 'beauty',
    sellingPrice: 6900,
    costPrice: 2200,
    status: 'ACTIVE',
    initialStock: 75,
  },
  {
    sku: 'NV-HM-007',
    name: 'Woven Storage Basket',
    nameAr: 'سلة تخزين منسوجة',
    description: 'Handwoven basket for blankets, magazines, or plants.',
    descriptionAr: 'سلة منسوجة يدوياً للبطانيات أو المجلات أو النباتات.',
    category: 'home',
    sellingPrice: 17900,
    costPrice: 6500,
    status: 'ACTIVE',
    initialStock: 14,
  },
];
